version: "3.8"

services:
  redis:
    image: redis:${REDIS_VERSION:-7}-alpine
    ports:
      - "6379:6379"
  sentinel:
    image: redis:${REDIS_VERSION:-7}-alpine
    entrypoint:
      - /bin/sh
      - -c
      - |
        redis-server --save "" --appendonly no --port 6380 &
        echo "sentinel monitor mymaster 127.0.0.1 6380 2\n" > sentinel.conf
        redis-server sentinel.conf --sentinel
    ports:
      - "6380:6380"
      - "26379:26379"
  cluster:
    image: redis:${REDIS_VERSION:-7}-alpine
    entrypoint:
      - /bin/sh
      - -c
      - |
        redis-server --port 7000 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7000.conf &
        redis-server --port 7001 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7001.conf &
        redis-server --port 7002 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7002.conf &
        while ! redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 127.0.0.1:7002 --cluster-yes; do sleep 1; done
        wait
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
